import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Emily Kiss Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/e.png" />
      </Head>
      <main>
        <h1 className="mt-8 text-center font-semibold tracking-tight text-white text-3xl">
          Hello there, I'm Emily!
        </h1>
        <span className="flex justify-center my-8">
          <Image
            src="/emily.jpg"
            alt="This is a picture of me."
            width={250}
            height={250}
            className="rounded-full"
          />
        </span>
        <h2 className="text-center font-semibold tracking-tight text-white text-3xl">
          I am a full-stack Software Engineer, a blank, and a
        </h2>
      </main>
    </div>
  )
}
