import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import "@fontsource/press-start-2p"
import Link from "next/link"

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Emily Kiss Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/emily.jpg" />
      </Head>
      <main>
        <div class="split left">
          <div className="flex justify-end">
            <Link href="/">
              <span className="px-3 py-2 text-xs justify-end uppercase font-bold leading-snug text-black hover:text-yellow-300 hover:animate-pulse">
                Home
              </span>
            </Link>

            <Link href="/about">
              <span className="px-3 py-2 text-xs uppercase font-bold leading-snug text-black hover:text-yellow-300 hover:animate-pulse">
                About
              </span>
            </Link>
          </div>
          {/* <div className="border-y-2 border-black text-black tracking-widest text-lg flex justify-center m-2">
            Software Engineer
          </div> */}
          <div class="centered">
            <h2></h2>
            <Image
              src="/emily.jpg"
              alt="This is a picture of me."
              width={1400}
              height={1450}
              className="opacity-100 hover:opacity-75"
            />
          </div>
          <br></br>
          <br></br>
          <br></br>
          <br></br>
        </div>

        <div class="split right">
          <div className="flex justify-start">
            <Link href="/work">
              <span className="px-3 py-2 justify-end text-xs uppercase font-bold leading-snug text-white hover:text-yellow-300 hover:animate-pulse">
                Work
              </span>
            </Link>

            <Link href="/contact">
              <span className="px-3 py-2 text-xs uppercase font-bold leading-snug text-white hover:text-yellow-300 hover:animate-pulse">
                Contact
              </span>
            </Link>
          </div>
          {/* <div className="border-y-2 border-white flex justify-center text-white tracking-widest text-lg m-2">
            UX Designer
          </div> */}
          <div class="centered">
            <h2 className="tracking-widest mb-4 text-7xl text-white">
              Emily Kiss
            </h2>
            <p className="tracking-widest text-white text-4xl italic mb-8">UX Engineer</p>
            <h6 className="text-center tracking-widest m-6">
              <a
                href="mailto:emilylanekiss@gmail.com? subject= subject text"
                className="tracking-widest text-white hover:text-black hover:bg-white rounded-full py-2 px-4 border border-white"
              >
                Collaborate
              </a>
            </h6>
          </div>
        </div>
      </main>
    </div>
  )
}
